import streamlit as st

st.set_page_config(page_title="Theoretical Concepts · TruthLens", page_icon="📚", layout="wide")

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
.page-header { background: linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%); border-radius: 20px; padding: 56px 48px 48px; margin-bottom: 48px; position: relative; overflow: hidden; }
.page-header::before { content: ""; position: absolute; top: -60px; right: -80px; width: 300px; height: 300px; background: radial-gradient(circle, rgba(167,139,250,0.2) 0%, transparent 70%); border-radius: 50%; }
.page-header .badge { display: inline-block; background: rgba(167,139,250,0.15); border: 1px solid rgba(167,139,250,0.35); color: #c4b5fd; font-size: 11px; font-weight: 700; letter-spacing: 2px; text-transform: uppercase; padding: 5px 16px; border-radius: 100px; margin-bottom: 20px; }
.page-header h1 { color:#fff; font-size:40px; font-weight:800; margin:0 0 14px; line-height:1.2; }
.page-header h1 span { background: linear-gradient(90deg,#a78bfa,#38bdf8); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
.page-header p { color:rgba(255,255,255,0.58); font-size:16px; max-width:660px; line-height:1.8; margin:0; }
.toc { background:#1a1a2e; border:1px solid rgba(255,255,255,0.07); border-radius:16px; padding:28px 32px; margin-bottom:40px; }
.toc h3 { color:#f1f5f9; font-size:15px; font-weight:700; margin:0 0 16px; text-transform:uppercase; letter-spacing:1px; }
.toc-grid { display:grid; grid-template-columns:repeat(2,1fr); gap:10px; }
.toc-item { display:flex; align-items:center; gap:12px; background:rgba(255,255,255,0.03); border:1px solid rgba(255,255,255,0.06); border-radius:10px; padding:12px 16px; }
.toc-item .ti-num { width:28px; height:28px; border-radius:8px; display:flex; align-items:center; justify-content:center; font-size:13px; font-weight:800; flex-shrink:0; }
.toc-item .ti-text { font-size:13px; color:rgba(255,255,255,0.7); font-weight:500; }
.ti-1 .ti-num { background:rgba(167,139,250,0.2); color:#c4b5fd; }
.ti-2 .ti-num { background:rgba(56,189,248,0.15); color:#7dd3fc; }
.ti-3 .ti-num { background:rgba(34,197,94,0.15); color:#86efac; }
.ti-4 .ti-num { background:rgba(251,191,36,0.15); color:#fcd34d; }
.concept-section { margin-bottom: 56px; }
.cs-title { display:flex; align-items:center; gap:16px; margin-bottom:20px; }
.cs-icon { width:52px; height:52px; border-radius:14px; display:flex; align-items:center; justify-content:center; font-size:24px; flex-shrink:0; }
.cs-icon.purple { background:linear-gradient(135deg,#4c1d95,#7c3aed); }
.cs-icon.blue { background:linear-gradient(135deg,#0c4a6e,#0ea5e9); }
.cs-icon.green { background:linear-gradient(135deg,#14532d,#16a34a); }
.cs-icon.amber { background:linear-gradient(135deg,#78350f,#d97706); }
.cs-title-text h2 { color:#f1f5f9; font-size:26px; font-weight:800; margin:0 0 4px; }
.cs-title-text .cs-sub { font-size:13px; color:rgba(255,255,255,0.35); font-weight:500; }
.card { background:#1a1a2e; border:1px solid rgba(255,255,255,0.07); border-radius:16px; padding:28px 32px; margin-bottom:14px; color:rgba(255,255,255,0.65); font-size:14.5px; line-height:1.85; }
.card h3 { color:#f1f5f9; font-size:16px; font-weight:700; margin:0 0 12px; }
.card strong { color:#e2e8f0; }
.card em { color:rgba(255,255,255,0.75); }
.card p { margin:0 0 12px; }
.card p:last-child { margin:0; }
.analogy-box { background:linear-gradient(135deg,rgba(124,58,237,0.1),rgba(56,189,248,0.07)); border:1px solid rgba(124,58,237,0.25); border-radius:12px; padding:20px 24px; margin-top:16px; }
.analogy-box .ab-label { font-size:10px; font-weight:800; letter-spacing:2px; text-transform:uppercase; color:#a78bfa; margin-bottom:8px; }
.analogy-box p { font-size:14px; color:rgba(255,255,255,0.65); line-height:1.7; margin:0; font-style:italic; }
.key-box { background:rgba(34,197,94,0.07); border:1px solid rgba(34,197,94,0.2); border-radius:12px; padding:18px 22px; margin-top:16px; }
.key-box .kb-label { font-size:10px; font-weight:800; letter-spacing:2px; text-transform:uppercase; color:#86efac; margin-bottom:8px; }
.key-box p { font-size:14px; color:rgba(255,255,255,0.6); line-height:1.7; margin:0; }
.two-col { display:grid; grid-template-columns:1fr 1fr; gap:14px; margin-bottom:14px; }
.example-box { background:#0d1117; border:1px solid rgba(255,255,255,0.07); border-radius:12px; padding:20px 24px; margin-top:16px; font-family:'Courier New',monospace; font-size:13px; line-height:1.9; }
.ex-label { font-family:'Inter',sans-serif; font-size:10px; font-weight:800; letter-spacing:2px; text-transform:uppercase; color:rgba(255,255,255,0.25); margin-bottom:12px; }
.ex-input { color:rgba(255,255,255,0.6); }
.ex-arrow { color:rgba(255,255,255,0.2); margin:6px 0; }
.ner-word { display:inline-block; padding:2px 8px; border-radius:5px; margin:1px; font-size:13px; }
.nw-person { background:rgba(167,139,250,0.2); color:#c4b5fd; border:1px solid rgba(167,139,250,0.3); }
.nw-org { background:rgba(56,189,248,0.15); color:#7dd3fc; border:1px solid rgba(56,189,248,0.25); }
.nw-gpe { background:rgba(34,197,94,0.15); color:#86efac; border:1px solid rgba(34,197,94,0.25); }
.nw-norp { background:rgba(239,68,68,0.15); color:#fca5a5; border:1px solid rgba(239,68,68,0.25); }
.nw-plain { color:rgba(255,255,255,0.5); }
.tag-legend { display:flex; gap:10px; flex-wrap:wrap; margin-top:12px; }
.tag-legend-item { display:flex; align-items:center; gap:6px; font-size:11px; color:rgba(255,255,255,0.4); }
.tl-dot { width:10px; height:10px; border-radius:3px; }
.attention-grid { display:grid; grid-template-columns:repeat(5,1fr); gap:6px; margin-top:16px; }
.attn-cell { border-radius:8px; padding:8px 4px; text-align:center; font-size:11px; font-weight:600; }
.pipeline-mini { display:flex; align-items:center; gap:8px; margin-top:16px; flex-wrap:wrap; }
.pm-box { background:rgba(255,255,255,0.04); border:1px solid rgba(255,255,255,0.08); border-radius:10px; padding:10px 16px; font-size:12px; color:rgba(255,255,255,0.6); font-weight:600; text-align:center; }
.pm-arrow { color:rgba(255,255,255,0.2); font-size:16px; }
.score-row { display:grid; grid-template-columns:repeat(4,1fr); gap:10px; margin-top:16px; }
.sr-card { border-radius:10px; padding:14px 12px; text-align:center; }
.sr-card .sr-n { font-size:20px; font-weight:800; margin-bottom:4px; }
.sr-card .sr-l { font-size:11px; color:rgba(255,255,255,0.4); line-height:1.4; }
.sr-10 { background:rgba(34,197,94,0.1); border:1px solid rgba(34,197,94,0.2); } .sr-10 .sr-n { color:#86efac; }
.sr-7 { background:rgba(251,191,36,0.08); border:1px solid rgba(251,191,36,0.2); } .sr-7 .sr-n { color:#fcd34d; }
.sr-4 { background:rgba(249,115,22,0.1); border:1px solid rgba(249,115,22,0.2); } .sr-4 .sr-n { color:#fdba74; }
.sr-1 { background:rgba(239,68,68,0.1); border:1px solid rgba(239,68,68,0.2); } .sr-1 .sr-n { color:#fca5a5; }
.divider-line { border:none; border-top:1px solid rgba(255,255,255,0.05); margin:48px 0; }
</style>
""", unsafe_allow_html=True)

# ── HERO
st.markdown('<div class="page-header"><div class="badge">📚 Theory</div><h1>The concepts behind <span>TruthLens</span></h1><p>A clear, comprehensive walkthrough of every technique used in this pipeline — written to explain not just what these methods do, but <em>why</em> they work and <em>how</em> they fit together to detect misinformation.</p></div>', unsafe_allow_html=True)

# ── TABLE OF CONTENTS
st.markdown('<div class="toc"><h3>Contents</h3><div class="toc-grid"><div class="toc-item ti-1"><div class="ti-num">1</div><div class="ti-text">Named Entity Recognition (NER)</div></div><div class="toc-item ti-2"><div class="ti-num">2</div><div class="ti-text">Sentiment Analysis &amp; Transfer Learning</div></div><div class="toc-item ti-3"><div class="ti-num">3</div><div class="ti-text">The Transformer Architecture</div></div><div class="toc-item ti-4"><div class="ti-num">4</div><div class="ti-text">Large Language Models &amp; Instruction Tuning</div></div></div></div>', unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════
# CONCEPT 1 — NER
# ══════════════════════════════════════════════════════════════════════
st.markdown('<div class="concept-section"><div class="cs-title"><div class="cs-icon purple">🏷️</div><div class="cs-title-text"><h2>1. Named Entity Recognition</h2><div class="cs-sub">spaCy · en_core_web_sm · Sequence Labelling</div></div></div></div>', unsafe_allow_html=True)

st.markdown('<div class="card"><h3>What is it?</h3><p><strong>Named Entity Recognition (NER)</strong> is one of the foundational tasks in Natural Language Processing. Its job is simple to state but technically rich to solve: given a sentence, <strong>find every word or phrase that refers to a real-world thing and label what kind of thing it is</strong>.</p><p>Those "things" are called <em>named entities</em> — people, organisations, countries, dates, laws, events, and more. In TruthLens we track five categories that are especially meaningful for political content: <strong>PERSON</strong>, <strong>ORG</strong>, <strong>GPE</strong> (geo-political entity), <strong>EVENT</strong>, and <strong>NORP</strong> (nationalities and political groups).</p><div class="analogy-box"><div class="ab-label">💡 Analogy</div><p>Think of NER as a highlighter that reads a paragraph and colour-codes every important name. Yellow for people, blue for organisations, green for places. Once everything is highlighted, you can immediately see at a glance: who is this about, which institutions are involved, and where is it happening?</p></div></div>', unsafe_allow_html=True)

st.markdown('<div class="card"><h3>A real example from the pipeline</h3><p>Take this sentence and watch how NER breaks it down:</p><div class="example-box"><div class="ex-label">Input text</div><div class="ex-input">"President Biden and NATO leaders met in Washington to discuss Russian disinformation."</div><div class="ex-arrow">↓ after NER</div><span class="ner-word nw-person">Biden</span> <span class="ner-word nw-plain">and</span> <span class="ner-word nw-org">NATO</span> <span class="ner-word nw-plain">leaders met in</span> <span class="ner-word nw-gpe">Washington</span> <span class="ner-word nw-plain">to discuss</span> <span class="ner-word nw-norp">Russian</span> <span class="ner-word nw-plain">disinformation.</span><div class="tag-legend"><div class="tag-legend-item"><div class="tl-dot" style="background:#a78bfa"></div>PERSON</div><div class="tag-legend-item"><div class="tl-dot" style="background:#38bdf8"></div>ORG</div><div class="tag-legend-item"><div class="tl-dot" style="background:#4ade80"></div>GPE</div><div class="tag-legend-item"><div class="tl-dot" style="background:#f87171"></div>NORP</div></div></div><div class="key-box"><div class="kb-label">🔑 Key insight</div><p>Notice that <em>"Russian"</em> is flagged as NORP (a nationality/political group), not just an adjective. This is exactly the kind of signal that matters in political misinformation — a post saturated with named political groups and institutions but citing no verifiable source is a strong red flag.</p></div></div>', unsafe_allow_html=True)

st.markdown('<div class="card"><h3>Why capitalisation matters — and why we preserve it</h3><p>spaCy\'s model was trained on text where <strong>capitalisation is a meaningful signal</strong>. The word <em>trump</em> (lowercase) can be a verb meaning "to outdo." The word <em>Trump</em> (capitalised) is a person. If we cleaned the text to lowercase first — as many NLP preprocessing steps do — the model would miss most named entities.</p><p>This is why TruthLens intentionally runs NER on the <strong>original, uncleaned text</strong>, while the sentiment model (which was trained on lowercase social-media text) receives the cleaned version. Each stage gets the format of text it was designed for.</p></div>', unsafe_allow_html=True)

st.markdown('<hr class="divider-line">', unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════
# CONCEPT 2 — SENTIMENT ANALYSIS
# ══════════════════════════════════════════════════════════════════════
st.markdown('<div class="concept-section"><div class="cs-title"><div class="cs-icon blue">🎭</div><div class="cs-title-text"><h2>2. Sentiment Analysis &amp; Transfer Learning</h2><div class="cs-sub">RoBERTa · cardiffnlp/twitter-roberta-base-sentiment-latest · Fine-tuning</div></div></div></div>', unsafe_allow_html=True)

st.markdown('<div class="card"><h3>What is Sentiment Analysis?</h3><p><strong>Sentiment Analysis</strong> is the task of automatically determining the emotional tone of a piece of text. At its simplest, it answers one question: <em>is this text positive, negative, or neutral?</em></p><p>This matters enormously for misinformation detection because <strong>false political content is almost never emotionally neutral</strong>. It is designed to provoke — to make you angry, afraid, or outraged — because those emotions are what make people share content without stopping to verify it. By measuring the sentiment and its confidence score, we add a quantified emotional signal to the LLM\'s reasoning.</p><div class="analogy-box"><div class="ab-label">💡 Analogy</div><p>Imagine reading a news headline with the volume turned up: "SHOCKING: Government SECRETLY approves mandatory X for ALL citizens starting NEXT MONTH." Even without knowing whether it\'s true, the all-caps, the exclamation, the urgency — all of it tells you this text is trying to make you feel something. Sentiment analysis measures exactly that volume level, automatically.</p></div></div>', unsafe_allow_html=True)

st.markdown('<div class="card"><h3>What is Transfer Learning — and why does it matter here?</h3><p>Training a sentiment model from scratch would require millions of labelled examples and enormous computing resources. <strong>Transfer Learning</strong> is the technique that makes this practical: you take a model that was already trained on a massive general dataset (learning grammar, meaning, context, and word relationships), and then <em>fine-tune</em> it on a smaller, task-specific dataset.</p><p>Think of it like hiring someone who already speaks the language fluently and teaching them a specialist job — versus teaching someone to speak the language AND do the job from zero.</p><p>The model we use — <strong>cardiffnlp/twitter-roberta-base-sentiment-latest</strong> — went through two phases:</p><div class="pipeline-mini"><div class="pm-box">Pre-trained on<br>billions of tokens<br>(general text)</div><div class="pm-arrow">→</div><div class="pm-box">Fine-tuned on<br>124M labelled tweets<br>(sentiment task)</div><div class="pm-arrow">→</div><div class="pm-box">Outputs:<br>Positive / Neutral / Negative<br>+ confidence score</div></div></div>', unsafe_allow_html=True)

st.markdown('<div class="card"><h3>Why RoBERTa and why tweets?</h3><p><strong>RoBERTa</strong> (Robustly Optimised BERT Approach) is a refined version of BERT — one of the most influential NLP models ever published. Compared to BERT, RoBERTa was trained on <em>more data</em>, for <em>longer</em>, with <em>larger batches</em>, and without one of BERT\'s pre-training objectives (Next Sentence Prediction) that turned out to be less helpful. The result is a stronger language representation.</p><p>The Cardiff NLP team fine-tuned RoBERTa specifically on tweets because tweets share the exact same linguistic style as Instagram captions: <strong>short, punchy, often unpunctuated, emotionally expressive</strong>. A model fine-tuned on formal news articles would perform poorly on this kind of content. Matching the training domain to the target domain is a fundamental principle of good NLP practice.</p><div class="key-box"><div class="kb-label">🔑 Key insight</div><p>The model returns a <em>confidence score</em> (0–1), not just a label. A post labelled "Negative" at 95% confidence is very different from one at 52% confidence. We pass the full numerical score to the LLM, so it can weight its assessment proportionally — not just react to a binary category.</p></div></div>', unsafe_allow_html=True)

st.markdown('<hr class="divider-line">', unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════
# CONCEPT 3 — TRANSFORMER
# ══════════════════════════════════════════════════════════════════════
st.markdown('<div class="concept-section"><div class="cs-title"><div class="cs-icon green">⚡</div><div class="cs-title-text"><h2>3. The Transformer Architecture</h2><div class="cs-sub">Vaswani et al. 2017 · Self-Attention · The foundation of modern NLP</div></div></div></div>', unsafe_allow_html=True)

st.markdown('<div class="card"><h3>Why did Transformers replace everything before them?</h3><p>Before 2017, most NLP systems used <strong>Recurrent Neural Networks (RNNs)</strong> — models that read text word by word, left to right, maintaining a "memory" of what came before. This worked, but it had a critical flaw: by the time the model reached the end of a long sentence, the signal from the beginning had been compressed and distorted through dozens of computation steps. Long-range dependencies — like knowing that a pronoun at the end of a paragraph refers to a name mentioned in the first sentence — were very difficult to learn.</p><p>The <strong>Transformer</strong>, introduced in the paper "Attention Is All You Need" (Vaswani et al., 2017), solved this by throwing out recurrence entirely. Instead of reading left to right, it reads <em>all words simultaneously</em> and learns which words should pay attention to which other words.</p><div class="analogy-box"><div class="ab-label">💡 Analogy</div><p>Imagine reading a book two ways. Method 1 (RNN): cover everything with your hand, reveal one word at a time, try to remember everything important as you go. Method 2 (Transformer): see the entire page at once, and for each word, instantly see how it connects to every other word on the page. Method 2 is obviously more powerful — that is the core intuition behind the Transformer.</p></div></div>', unsafe_allow_html=True)

st.markdown('<div class="card"><h3>Self-Attention: the key mechanism</h3><p>The core of the Transformer is <strong>Self-Attention</strong>. For every word in the input, the model computes a score against every other word — "how much should I pay attention to this other word when understanding the current word?" These scores are then used to create a weighted representation of the whole sentence, from the perspective of each individual word.</p><p>For example, in the sentence <em>"The government denied the allegations that it had hidden the report"</em>, when processing the word <em>"it"</em>, self-attention learns to focus strongly on <em>"government"</em> — correctly resolving the pronoun reference across many words of distance. An RNN would struggle with this. A Transformer handles it naturally.</p><p>The model uses <strong>multiple attention heads</strong> running in parallel — each learning a different kind of relationship (syntactic, semantic, coreference, etc.) — and combines their outputs. This is called <em>Multi-Head Self-Attention</em>.</p><div class="attention-grid"><div class="attn-cell" style="background:rgba(167,139,250,0.35);color:#e9d5ff;">The</div><div class="attn-cell" style="background:rgba(167,139,250,0.6);color:#e9d5ff;">government</div><div class="attn-cell" style="background:rgba(167,139,250,0.15);color:#c4b5fd;">denied</div><div class="attn-cell" style="background:rgba(167,139,250,0.1);color:#a78bfa;">the</div><div class="attn-cell" style="background:rgba(167,139,250,0.1);color:#a78bfa;">allegations</div></div><div style="font-size:11px;color:rgba(255,255,255,0.3);margin-top:8px;font-style:italic;">Attention weights when the model processes "it" — darker = more attention paid. "government" scores highest, correctly identifying the referent.</div></div>', unsafe_allow_html=True)

st.markdown('<div class="card"><h3>BERT, RoBERTa, and LLaMA — what is the difference?</h3><p>All three are Transformer-based, but they differ in <em>architecture direction</em> and <em>training objective</em>:</p><div class="two-col"><div class="card" style="margin-bottom:0;border-color:rgba(56,189,248,0.2);"><h3 style="color:#7dd3fc;">BERT &amp; RoBERTa — Encoders</h3><p>Read the text in <strong>both directions</strong> simultaneously (bidirectional). Trained to predict masked words: given "The [MASK] denied the claim", predict "government". This makes them excellent at <em>understanding</em> text — classification, sentiment, NER.</p><p>RoBERTa is simply BERT trained better: more data, longer training, smarter batching. Used in TruthLens for sentiment analysis.</p></div><div class="card" style="margin-bottom:0;border-color:rgba(34,197,94,0.2);"><h3 style="color:#86efac;">LLaMA — Decoder</h3><p>Reads left to right and is trained to <strong>predict the next word</strong>. This makes it excellent at <em>generating</em> text — answering questions, following instructions, producing structured output like JSON.</p><p>LLaMA 3.3 70B has 70 billion parameters (learned values) and has been instruction-tuned to follow complex prompts. Used in TruthLens for credibility scoring.</p></div></div></div>', unsafe_allow_html=True)

st.markdown('<hr class="divider-line">', unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════
# CONCEPT 4 — LLMs
# ══════════════════════════════════════════════════════════════════════
st.markdown('<div class="concept-section"><div class="cs-title"><div class="cs-icon amber">🤖</div><div class="cs-title-text"><h2>4. Large Language Models &amp; Instruction Tuning</h2><div class="cs-sub">Llama 3.3 70B · RLHF · Prompt Engineering · Structured Output</div></div></div></div>', unsafe_allow_html=True)

st.markdown('<div class="card"><h3>What makes a language model "large"?</h3><p>A <strong>Large Language Model (LLM)</strong> is a Transformer decoder trained on an internet-scale corpus — trillions of words from books, articles, websites, code, and conversations. The goal during pre-training is deceptively simple: <strong>predict the next word</strong>. But to do this well across all topics, the model is forced to learn grammar, facts, reasoning patterns, logical structure, and even common sense.</p><p>"Large" refers to the number of <strong>parameters</strong> — the numerical weights inside the network that are adjusted during training. Llama 3.3 70B has <strong>70 billion parameters</strong>. To understand the scale: a single human brain has roughly 100 trillion synapses. A 70B model is not a brain, but its capacity to represent and manipulate information is genuinely vast.</p><div class="analogy-box"><div class="ab-label">💡 Analogy</div><p>Pre-training an LLM is like having someone read the entire internet, every book in every library, and every academic paper ever published — and then asking them questions. The reading is the pre-training. The answers are inference. The 70 billion parameters are the compressed representation of everything read.</p></div></div>', unsafe_allow_html=True)

st.markdown('<div class="card"><h3>Instruction Tuning: from text predictor to assistant</h3><p>A raw pre-trained model just completes text — it continues whatever you give it, without any sense of being helpful or following instructions. To turn it into a useful assistant, a second training phase is applied: <strong>Instruction Tuning</strong>.</p><p>The most effective form is <strong>Reinforcement Learning from Human Feedback (RLHF)</strong>. Human labellers rate model outputs for helpfulness, honesty, and harmlessness. A separate "reward model" is trained on these ratings, and the main LLM is then fine-tuned to maximise the reward model\'s score. The result is a model that follows instructions, stays on topic, and produces structured, reliable output.</p><p>This is why we can tell Llama 3.3 70B: <em>"respond only with a JSON object in this exact schema"</em> — and it reliably does so. Without instruction tuning, the model would simply continue the conversation as free text.</p></div>', unsafe_allow_html=True)

st.markdown('<div class="card"><h3>How TruthLens uses the LLM: prompt engineering</h3><p><strong>Prompt Engineering</strong> is the practice of carefully designing the input text you send to an LLM to get the most accurate, useful output. In TruthLens, the prompt we send to Llama 3.3 70B is not just the raw post — it is a structured document containing:</p><div class="pipeline-mini"><div class="pm-box">System prompt<br>(role + schema<br>+ scoring guide)</div><div class="pm-arrow">+</div><div class="pm-box">Raw post text<br>(up to 800 chars)</div><div class="pm-arrow">+</div><div class="pm-box">NER output<br>(persons, orgs,<br>locations, groups)</div><div class="pm-arrow">+</div><div class="pm-box">Sentiment<br>(label +<br>confidence)</div></div><p style="margin-top:16px;">The system prompt defines the model\'s role ("you are a fact-checking assistant"), gives it the exact JSON schema to follow, and provides a calibrated scoring guide (8-10 = credible, 0-1 = misinformation). This combination of <em>role assignment</em>, <em>structured output specification</em>, and <em>grounded metadata</em> is what makes the LLM\'s verdict reliable and consistent rather than arbitrary.</p><div class="score-row"><div class="sr-card sr-10"><div class="sr-n">8–10</div><div class="sr-l">Factual, verifiable, balanced</div></div><div class="sr-card sr-7"><div class="sr-n">5–7</div><div class="sr-l">Mostly accurate, minor issues</div></div><div class="sr-card sr-4"><div class="sr-n">2–4</div><div class="sr-l">Misleading or unverified</div></div><div class="sr-card sr-1"><div class="sr-n">0–1</div><div class="sr-l">Clear misinformation</div></div></div></div>', unsafe_allow_html=True)

st.markdown('<div class="card"><h3>Why combine three techniques instead of using just the LLM?</h3><p>An LLM alone could attempt to assess credibility — but it would be making purely subjective judgements based on pattern matching, with no structured signals to anchor its reasoning. By running NER and sentiment first, we give the LLM <strong>objective, measurable inputs</strong>:</p><p>— <strong>NER</strong> tells it exactly which political actors, organisations, and groups are involved, and how many named entities appear relative to the length of the text.</p><p>— <strong>Sentiment</strong> gives it a calibrated, model-based measure of emotional intensity — not just "this sounds angry" but "this is Negative at 94% confidence."</p><p>The LLM then acts as a reasoning layer that <em>synthesises</em> these signals into a verdict, the way a human expert analyst would combine multiple data points before reaching a conclusion. The result is more accurate, more consistent, and more explainable than any single technique alone.</p><div class="key-box"><div class="kb-label">🔑 The core principle</div><p>Each of the three stages compensates for the weaknesses of the others. NER is fast and precise but has no understanding of truthfulness. Sentiment is excellent at detecting emotional manipulation but cannot evaluate factual accuracy. The LLM can reason about both — but needs grounded inputs to do so reliably. Together, the pipeline is greater than the sum of its parts.</p></div></div>', unsafe_allow_html=True)
